services:
  - type: web
    name: pulse-chat-app
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      npm ci
      npm --prefix frontend ci --include=dev
      npm --prefix frontend run build
      npm --prefix backend ci
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /health